// List of the first 151 Pokemon of the Kanto region 
let pokemonList = [
    { name: "Bulbasaur", height: 7, weight: 69, types: ['grass', 'poison'], japaneseName: "フシギダネ" },
    { name: "Ivysaur", height: 10, weight: 130, types: ['grass', 'poison'], japaneseName: "フシギソウ" },
    { name: "Venusaur", height: 20, weight: 1000, types: ['grass', 'poison'], japaneseName: "フシギバナ" },
    { name: "Charmander", height: 6, weight: 85, types: ['fire'], japaneseName: "ヒトカゲ" },
    { name: "Charmeleon", height: 11, weight: 190, types: ['fire'], japaneseName: "リザード" },
    { name: "Charizard", height: 17, weight: 905, types: ['fire', 'flying'], japaneseName: "リザードン" },
    { name: "Squirtle", height: 5, weight: 90, types: ['water'], japaneseName: "ゼニガメ" },
    { name: "Wartortle", height: 10, weight: 225, types: ['water'], japaneseName: "カメール" },
    { name: "Blastoise", height: 16, weight: 855, types: ['water'], japaneseName: "カメックス" },
    { name: "Caterpie", height: 3, weight: 29, types: ['bug'], japaneseName: "キャタピー" },
    { name: "Metapod", height: 7, weight: 99, types: ['bug'], japaneseName: "トランセル" },
    { name: "Butterfree", height: 11, weight: 320, types: ['bug', 'flying'], japaneseName: "バタフリー" },
    { name: "Weedle", height: 3, weight: 32, types: ['bug', 'poison'], japaneseName: "ビードル" },
    { name: "Kakuna", height: 6, weight: 100, types: ['bug', 'poison'], japaneseName: "コクーン" },
    { name: "Beedrill", height: 10, weight: 295, types: ['bug', 'poison'], japaneseName: "スピアー" },
    { name: "Pidgey", height: 3, weight: 18, types: ['normal', 'flying'], japaneseName: "ポッポ" },
    { name: "Pidgeotto", height: 11, weight: 300, types: ['normal', 'flying'], japaneseName: "ピジョン" },
    { name: "Pidgeot", height: 15, weight: 395, types: ['normal', 'flying'], japaneseName: "ピジョット" },
    { name: "Rattata", height: 3, weight: 35, types: ['normal'], japaneseName: "コラッタ" },
    { name: "Raticate", height: 7, weight: 185, types: ['normal'], japaneseName: "ラッタ" },
    { name: "Spearow", height: 3, weight: 20, types: ['normal', 'flying'], japaneseName: "オニスズメ" },
    { name: "Fearow", height: 12, weight: 380, types: ['normal', 'flying'], japaneseName: "オニドリル" },
    { name: "Ekans", height: 20, weight: 69, types: ['poison'], japaneseName: "アーボ" },
    { name: "Arbok", height: 35, weight: 650, types: ['poison'], japaneseName: "アーボック" },
    { name: "Pikachu", height: 4, weight: 60, types: ['electric'], japaneseName: "ピカチュウ" },
    { name: "Raichu", height: 8, weight: 300, types: ['electric'], japaneseName: "ライチュウ" },
    { name: "Sandshrew", height: 6, weight: 120, types: ['ground'], japaneseName: "サンド" },
    { name: "Sandslash", height: 10, weight: 295, types: ['ground'], japaneseName: "サンドパン" },
    { name: "Nidoran♀", height: 4, weight: 70, types: ['poison'], japaneseName: "ニドラン♀" },
    { name: "Nidorina", height: 8, weight: 200, types: ['poison'], japaneseName: "ニドリーナ" },
    { name: "Nidoqueen", height: 13, weight: 600, types: ['poison', 'ground'], japaneseName: "ニドクイン" },
    { name: "Nidoking", height: 14, weight: 620, types: ['poison', 'ground'], japaneseName: "ニドキング" },
    { name: "Clefairy", height: 6, weight: 75, types: ['fairy'], japaneseName: "ピッピ" },
    { name: "Clefable", height: 13, weight: 400, types: ['fairy'], japaneseName: "ピクシー" },
    { name: "Vulpix", height: 6, weight: 99, types: ['fire'], japaneseName: "ロコン" },
    { name: "Ninetales", height: 11, weight: 199, types: ['fire'], japaneseName: "キュウコン" },
    { name: "Jigglypuff", height: 5, weight: 55, types: ['normal', 'fairy'], japaneseName: "プリン" },
    { name: "Wigglytuff", height: 10, weight: 120, types: ['normal', 'fairy'], japaneseName: "プクリン" },
    { name: "Zubat", height: 8, weight: 75, types: ['poison', 'flying'], japaneseName: "ズバット" },
    { name: "Golbat", height: 16, weight: 550, types: ['poison', 'flying'], japaneseName: "ゴルバット" },
    { name: "Oddish", height: 5, weight: 54, types: ['grass', 'poison'], japaneseName: "ナゾノクサ" },
    { name: "Gloom", height: 8, weight: 86, types: ['grass', 'poison'], japaneseName: "クサイハナ" },
    { name: "Vileplume", height: 12, weight: 186, types: ['grass', 'poison'], japaneseName: "ラフレシア" },
    { name: "Paras", height: 3, weight: 54, types: ['bug', 'grass'], japaneseName: "パラス" },
    { name: "Parasect", height: 10, weight: 295, types: ['bug', 'grass'], japaneseName: "パラセクト" },
    { name: "Venonat", height: 10, weight: 300, types: ['bug', 'poison'], japaneseName: "コンパン" },
    { name: "Venomoth", height: 15, weight: 125, types: ['bug', 'poison'], japaneseName: "モルフォン" },
    { name: "Diglett", height: 2, weight: 8, types: ['ground'], japaneseName: "ディグダ" },
    { name: "Dugtrio", height: 7, weight: 333, types: ['ground'], japaneseName: "ダグトリオ" },
    { name: "Meowth", height: 4, weight: 42, types: ['normal'], japaneseName: "ニャース" },
    { name: "Persian", height: 10, weight: 320, types: ['normal'], japaneseName: "ペルシアン" },
    { name: "Psyduck", height: 8, weight: 196, types: ['water'], japaneseName: "コダック" },
    { name: "Golduck", height: 17, weight: 766, types: ['water'], japaneseName: "ゴルダック" },
    { name: "Mankey", height: 5, weight: 280, types: ['fighting'], japaneseName: "マンキー" },
    { name: "Primeape", height: 10, weight: 320, types: ['fighting'], japaneseName: "オコリザル" },
    { name: "Growlithe", height: 7, weight: 190, types: ['fire'], japaneseName: "ガーディ" },
    { name: "Arcanine", height: 19, weight: 1550, types: ['fire'], japaneseName: "ウインディ" },
    { name: "Poliwag", height: 6, weight: 124, types: ['water'], japaneseName: "ニョロモ" },
    { name: "Poliwhirl", height: 10, weight: 200, types: ['water'], japaneseName: "ニョロゾ" },
    { name: "Poliwrath", height: 13, weight: 540, types: ['water', 'fighting'], japaneseName: "ニョロボン" },
    { name: "Abra", height: 9, weight: 195, types: ['psychic'], japaneseName: "ケーシィ" },
    { name: "Kadabra", height: 13, weight: 565, types: ['psychic'], japaneseName: "ユンゲラー" },
    { name: "Alakazam", height: 15, weight: 480, types: ['psychic'], japaneseName: "フーディン" },
    { name: "Machop", height: 8, weight: 195, types: ['fighting'], japaneseName: "ワンリキー" },
    { name: "Machoke", height: 15, weight: 705, types: ['fighting'], japaneseName: "ゴーリキー" },
    { name: "Machamp", height: 16, weight: 1300, types: ['fighting'], japaneseName: "カイリキー" },
    { name: "Bellsprout", height: 7, weight: 40, types: ['grass', 'poison'], japaneseName: "マダツボミ" },
    { name: "Weepinbell", height: 10, weight: 64, types: ['grass', 'poison'], japaneseName: "ウツドン" },
    { name: "Victreebel", height: 17, weight: 155, types: ['grass', 'poison'], japaneseName: "ウツボット" },
    { name: "Tentacool", height: 9, weight: 455, types: ['water', 'poison'], japaneseName: "メノクラゲ" },
    { name: "Tentacruel", height: 16, weight: 550, types: ['water', 'poison'], japaneseName: "ドククラゲ" },
    { name: "Geodude", height: 4, weight: 200, types: ['rock', 'ground'], japaneseName: "イシツブテ" },
    { name: "Graveler", height: 10, weight: 1050, types: ['rock', 'ground'], japaneseName: "ゴローン" },
    { name: "Golem", height: 14, weight: 3000, types: ['rock', 'ground'], japaneseName: "ゴローニャ" },
    { name: "Ponyta", height: 10, weight: 300, types: ['fire'], japaneseName: "ポニータ" },
    { name: "Rapidash", height: 17, weight: 950, types: ['fire'], japaneseName: "ギャロップ" },
    { name: "Slowpoke", height: 12, weight: 360, types: ['water', 'psychic'], japaneseName: "ヤドン" },
    { name: "Slowbro", height: 16, weight: 785, types: ['water', 'psychic'], japaneseName: "ヤドラン" },
    { name: "Magnemite", height: 3, weight: 60, types: ['electric', 'steel'], japaneseName: "コイル" },
    { name: "Magneton", height: 10, weight: 600, types: ['electric', 'steel'], japaneseName: "レアコイル" },
    { name: "Farfetch'd", height: 8, weight: 150, types: ['normal', 'flying'], japaneseName: "カモネギ" },
    { name: "Doduo", height: 14, weight: 392, types: ['normal', 'flying'], japaneseName: "ドードー" },
    { name: "Dodrio", height: 18, weight: 852, types: ['normal', 'flying'], japaneseName: "ドードリオ" },
    { name: "Seel", height: 11, weight: 900, types: ['water'], japaneseName: "パウワウ" },
    { name: "Dewgong", height: 17, weight: 1200, types: ['water', 'ice'], japaneseName: "ジュゴン" },
    { name: "Grimer", height: 9, weight: 300, types: ['poison'], japaneseName: "ベトベター" },
    { name: "Muk", height: 12, weight: 300, types: ['poison'], japaneseName: "ベトベトン" },
    { name: "Shellder", height: 3, weight: 40, types: ['water'], japaneseName: "シェルダー" },
    { name: "Cloyster", height: 15, weight: 1325, types: ['water', 'ice'], japaneseName: "パルシェン" },
    { name: "Electrode", height: 12, weight: 666, types: ['electric'], japaneseName: "マルマイン" },
    { name: "Exeggcute", height: 4, weight: 25, types: ['grass', 'psychic'], japaneseName: "タマタマ" },
    { name: "Exeggutor", height: 20, weight: 1200, types: ['grass', 'psychic'], japaneseName: "ナッシー" },
    { name: "Cubone", height: 4, weight: 65, types: ['ground'], japaneseName: "カラカラ" },
    { name: "Marowak", height: 10, weight: 450, types: ['ground'], japaneseName: "ガラガラ" },
    { name: "Hitmonlee", height: 15, weight: 498, types: ['fighting'], japaneseName: "サワムラー" },
    { name: "Hitmonchan", height: 14, weight: 502, types: ['fighting'], japaneseName: "エビワラー" },
    { name: "Lickitung", height: 12, weight: 655, types: ['normal'], japaneseName: "ベロリンガ" },
    { name: "Koffing", height: 6, weight: 10, types: ['poison'], japaneseName: "ドガース" },
    { name: "Weezing", height: 12, weight: 95, types: ['poison'], japaneseName: "マタドガス" },
    { name: "Rhyhorn", height: 10, weight: 1150, types: ['ground', 'rock'], japaneseName: "サイホーン" },
    { name: "Rhydon", height: 19, weight: 1200, types: ['ground', 'rock'], japaneseName: "サイドン" },
    { name: "Chansey", height: 11, weight: 346, types: ['normal'], japaneseName: "ラッキー" },
    { name: "Tangela", height: 10, weight: 350, types: ['grass'], japaneseName: "モンジャラ" },
    { name: "Kangaskhan", height: 22, weight: 800, types: ['normal'], japaneseName: "ガルーラ" },
    { name: "Horsea", height: 4, weight: 80, types: ['water'], japaneseName: "タッツー" },
    { name: "Seadra", height: 12, weight: 250, types: ['water'], japaneseName: "シードラ" },
    { name: "Goldeen", height: 6, weight: 150, types: ['water'], japaneseName: "トサキント" },
    { name: "Seaking", height: 13, weight: 390, types: ['water'], japaneseName: "アズマオウ" },
    { name: "Staryu", height: 8, weight: 345, types: ['water'], japaneseName: "ヒトデマン" },
    { name: "Starmie", height: 11, weight: 800, types: ['water', 'psychic'], japaneseName: "スターミー" },
    { name: "Mr. Mime", height: 13, weight: 545, types: ['psychic', 'fairy'], japaneseName: "バリヤード" },
    { name: "Scyther", height: 15, weight: 560, types: ['bug', 'flying'], japaneseName: "ストライク" },
    { name: "Jynx", height: 14, weight: 406, types: ['ice', 'psychic'], japaneseName: "ルージュラ" },
    { name: "Electabuzz", height: 11, weight: 300, types: ['electric'], japaneseName: "エレブー" },
    { name: "Magmar", height: 13, weight: 445, types: ['fire'], japaneseName: "ブーバー" },
    { name: "Pinsir", height: 15, weight: 550, types: ['bug'], japaneseName: "カイロス" },
    { name: "Tauros", height: 14, weight: 884, types: ['normal'], japaneseName: "ケンタロス" },
    { name: "Magikarp", height: 9, weight: 100, types: ['water'], japaneseName: "コイキング" },
    { name: "Gyarados", height: 65, weight: 2350, types: ['water', 'flying'], japaneseName: "ギャラドス" },
    { name: "Lapras", height: 25, weight: 2200, types: ['water', 'ice'], japaneseName: "ラプラス" },
    { name: "Ditto", height: 3, weight: 40, types: ['normal'], japaneseName: "メタモン" },
    { name: "Eevee", height: 3, weight: 65, types: ['normal'], japaneseName: "イーブイ" },
    { name: "Vaporeon", height: 10, weight: 290, types: ['water'], japaneseName: "シャワーズ" },
    { name: "Jolteon", height: 8, weight: 245, types: ['electric'], japaneseName: "サンダース" },
    { name: "Flareon", height: 9, weight: 250, types: ['fire'], japaneseName: "ブースター" },
    { name: "Porygon", height: 8, weight: 365, types: ['normal'], japaneseName: "ポリゴン" },
    { name: "Omanyte", height: 4, weight: 75, types: ['rock', 'water'], japaneseName: "オムナイト" },
    { name: "Omastar", height: 10, weight: 350, types: ['rock', 'water'], japaneseName: "オムスター" },
    { name: "Kabuto", height: 5, weight: 115, types: ['rock', 'water'], japaneseName: "カブト" },
    { name: "Kabutops", height: 13, weight: 405, types: ['rock', 'water'], japaneseName: "カブトプス" },
    { name: "Aerodactyl", height: 18, weight: 590, types: ['rock', 'flying'], japaneseName: "プテラ" },
    { name: "Snorlax", height: 21, weight: 4600, types: ['normal'], japaneseName: "カビゴン" },
    { name: "Articuno", height: 17, weight: 554, types: ['ice', 'flying'], japaneseName: "フリーザー" },
    { name: "Zapdos", height: 16, weight: 526, types: ['electric', 'flying'], japaneseName: "サンダー" },
    { name: "Moltres", height: 20, weight: 600, types: ['fire', 'flying'], japaneseName: "ファイヤー" },
    { name: "Dratini", height: 18, weight: 33, types: ['dragon'], japaneseName: "ミニリュウ" },
    { name: "Dragonair", height: 40, weight: 165, types: ['dragon'], japaneseName: "ハクリュー" },
    { name: "Dragonite", height: 22, weight: 2100, types: ['dragon', 'flying'], japaneseName: "カイリュー" },
    { name: "Mewtwo", height: 20, weight: 1220, types: ['psychic'], japaneseName: "ミュウツー" },
    { name: "Mew", height: 4, weight: 40, types: ['psychic'], japaneseName: "ミュウ" },
];
